version: "3.7"
services:
    postgres:
        build:
            context: .
            dockerfile: database.dockerfile
        restart: always
        shm_size: 2gb
        env_file:
            - ./backend/.env
        volumes:
            - ./deploy/pg-init.sh:/docker-entrypoint-initdb.d/pg-init.sh
            - ./backend/main/management/backup_helper.py:/backup_helper.py
            - ./postgres-data:/var/lib/postgresql/data

    backend:
        build:
            context: .
            dockerfile: backend.dockerfile
        restart: always
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/:/patentinspector
        depends_on:
            - postgres
        links:
            - postgres

    certs:
        image: ubuntu
        volumes:
            - .:/app
        command: bash -c 'cd app && ./deploy/dummy-certs.sh'

    frontend:
        build:
            context: .
            dockerfile: frontend.dockerfile
        env_file:
            - ./backend/.env
        volumes:
            - ./frontend-dist/:/frontend/dist

    nginx:
        image: nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
            - .:/app
        depends_on:
            certs:
                condition: service_completed_successfully
            frontend:
                condition: service_completed_successfully
            backend:
                condition: service_started
        links:
            - backend
